version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.3-node
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-bundle-{{ checksum "Gemfile.lock" }}
      - run:
          name: Bundle Install
          command: bundle check || bundle install
      - save_cache:
          key: v1-bundle-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle
      - run:
          name: Build
          command: make build
      - run:
          name: Test
          command: make test
      # Saves the build files so they can be recalled in other jobs
      - persist_to_workspace:
          root: .
          paths:
            - _site

  deploy:
    docker:
      - image: circleci/ruby:2.3-node
    environment:
      #GITHUB_REPO: adborden/odca-jekyll
    steps:
      - checkout
      - attach_workspace:
          at: .
      - deploy:
          name: Deploy to GH pages
          command: _bin/deploy.sh


workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: feature/ci-cd
